src/Entity/Core/Employee.php
<?php

/*
 * This file is part of the Docudex project.
 *
 * (c) Devnet Limited <http://www.devnetlimited.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity\Core;

use App\Entity\Admin\Bank;
use App\Entity\Admin\Location;
use App\Entity\Domain\Customer;
use App\Entity\User;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**

 * @ORM\Table(name="core_employee")
 * @ORM\Entity(repositoryClass="App\Repository\Core\EmployeeRepository")
 * @UniqueEntity(fields="employeeId",message="This employee id must be unique")
 * @ORM\HasLifecycleCallbacks
 */
class Employee
{
    /**
     * @var integer
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue
     */
    private $id;


    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", nullable=true)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="fatherName", type="string", nullable=true)
     */
    private $fatherName;

    /**
     * @var string
     *
     * @ORM\Column(name="motherName", type="string", nullable=true)
     */
    private $motherName;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $designation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $operationalDesignation;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $department;



    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Domain\Branch")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="branch_id", referencedColumnName="id", onDelete="SET NULL", nullable=true)
     * })
     */
    protected $company;


    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Admin\Bank")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $bank;


    /**
     * @var Setting
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $section;

    /**
     * @var Setting
     * @ORM\ManyToOne(targetEntity="App\Entity\Core\Setting")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    protected $category;


    /**
     * @var string
     *
     * @ORM\Column(name="mobile", type="string", length=15, nullable=true)
     */
    private $mobile;

    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $bankName;


    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $branchName;

    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $bankAccountNo;


     /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $routingNo;


     /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $ebl;

    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $eblBankName = "Eastern Bank Ltd";


    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $eblBranchName;


    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $eblRoutingNo;


     /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true)
     */
    private $doj;


    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", nullable=true)
     */
    private $email;


    /**
     * @var text
     *
     * @ORM\Column(name="address", type="text", nullable=true)
     */
    private $address;


    /**
     * @var string
     *
     * @ORM\Column(name="postalCode", type="string", nullable=true)
     */
    private $postalCode;



    /**
     * @var string
     *
     * @ORM\Column(name="nid", type="string", nullable=true)
     */
    private $nid;


    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", nullable=true)
     */
    private $gender;


    /**
     * @var string
     *
     * @ORM\Column(name="bloodGroup", type="string", nullable=true)
     */
    private $bloodGroup;


    /**
     * @var string
     *
     * @ORM\Column(type="string", nullable=true, unique=true)
     */
    private $employeeId;



    /**
     * @var string
     *
     * @ORM\Column(name="employeeType", type="string", nullable=true)
     */
    private $employeeType;


    /**
     * @var string
     *
     * @ORM\Column(name="joiningDate", type="datetime", nullable=true)
     */
    private $joiningDate;

    /**
     * @var string
     *
     * @ORM\Column(name="leaveDate", type="datetime", nullable=true)
     */
    private $leaveDate;


    /**
     * @var string
     *
     * @ORM\Column(name="accountNo", type="string", length=255, nullable = true)
     */
    private $accountNo;


    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $dateOfBirth;

    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $effectiveDate;


    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $salary;



    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $leaveStatus;



    /**
     * @var string
     *
     * @ORM\Column(type="string",nullable=true)
     */
    private $accountNumber;


     /**
     * @var boolean
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $removeImage = true;

    /**
     * @var boolean
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $status = true;

     /**
     * @var boolean
     *
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $isDelete = false;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $path;

    /**
     * @var string
     *
     * @ORM\Column(type="text", nullable=true)
     */
    private $signaturePath;


    /**
     * @Assert\File(maxSize="1M")
     */
    protected $file;

     /**
     * @Assert\File(maxSize="1M")
     */
    protected $signatureFile;

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Sets file.
     *
     * @param Profile $file
     */
    public function setFile(UploadedFile $file = null)
    {
        $this->file = $file;
    }

    /**
     * Get file.
     *
     * @return Profile
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * Sets signatureFile.
     *
     * @param Profile $signatureFile
     */
    public function setSignatureFile(UploadedFile $signatureFile = null)
    {
        $this->signatureFile = $signatureFile;
    }

    /**
     * Get signatureFile.
     *
     * @return Profile
     */
    public function getSignatureFile()
    {
        return $this->signatureFile;
    }

    public function getAbsolutePath()
    {
        return null === $this->path
            ? null
            : $this->getUploadRootDir().'/'.$this->path;
    }

    public function getAbsoluteSignaturePath()
    {
        return null === $this->signaturePath
            ? null
            : $this->getUploadRootDir().'/'.$this->signaturePath;
    }

    public function getWebPath()
    {
        return null === $this->path
            ? null
            : $this->getUploadDir().'/' . $this->path;
    }

    protected function getUploadRootDir()
    {
        if(!file_exists( $this->getUploadDir())){
            mkdir( $this->getUploadDir(), 0777, true);
        }
        return __DIR__ . '/../../../public/' . $this->getUploadDir();
    }

    protected function getUploadDir()
    {
        return 'uploads/user/';
    }

    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath() and  file_exists($this->getAbsolutePath())) {
            unlink($file);
            $this->path = null ;
        }
    }

    public function removeSignatureUpload()
    {
        if ($file = $this->getAbsoluteSignaturePath()) {
            unlink($file);
            $this->path = null ;
        }
    }

    public function upload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getFile()) {
            return;
        }
        // use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to
        $filename = date('YmdHmi') . "_" . $this->getFile()->getClientOriginalName();
        $this->getFile()->move(
            $this->getUploadRootDir(),
            $filename
        );

        // set the path property to the filename where you've saved the file
        $this->path = $filename ;

        // clean up the file property as you won't need it anymore
        $this->file = null;
    }

    public function signatureUpload()
    {
        // the file property can be empty if the field is not required
        if (null === $this->getSignatureFile()) {
            return;
        }
        // use the original file name here but you should
        // sanitize it at least to avoid any security issues

        // move takes the target directory and then the
        // target filename to move to
        $filename = date('YmdHmi') . "_" . $this->getSignatureFile()->getClientOriginalName();
        $this->getSignatureFile()->move(

templates/base.dist/nav-backup.html.twig
<header class="">
    <nav class="navbar navbar-expand-md white-font">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <div class="dropdown">
                <span  id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                   <img src="{{ asset('assets/images/app-icon.png') }}" style="height:40px"  />
                </span>
                <div class="dropdown-menu dropright" id="application">
                    <div class="dropdown-header text-center" id="application-inner">APPLICATIONS</div>

                </div>
            </div>
            <ul class="nav navbar-nav" style="margin-left:30px">
                {% if (is_granted("ROLE_DOMAIN") or is_granted("ROLE_CORE"))  %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ 'Inventory'|trans }}
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li class="dropdown-submenu">
                                <a class="dropdown-item dropdown-toggle" href="javascript:">{{ 'Setting'|trans }}</a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="">{{ ' Setting'|trans }}</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                {% endif %}
                {% if (is_granted("ROLE_ADMIN") or is_granted("ROLE_DOMAIN") or is_granted("ROLE_CORE"))  %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="javascript:" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Master Data
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            {% if (is_granted("ROLE_DOMAIN") or is_granted("ROLE_USER"))  %}
                                <li><a class="dropdown-item" href="{{ path('core_user') }}">Manage Employee</a></li>
                                <li><a class="dropdown-item" href="{{ path('core_agent') }}">Manage Agent</a></li>
                                <li><a class="dropdown-item" href="{{ path('core_setting') }}">{{ 'Core Setting'|trans }}</a></li>
                                <li><a class="dropdown-item" href="{{ path('admin_location_index') }}">{{ 'Location'|trans }}</a></li>
                            {% endif %}
                            {# {% if (is_granted("ROLE_DOMAIN") or is_granted("ROLE_ADMIN"))  %}
                                 <li><a class="dropdown-item" href="{{ path('core_domain_terminal') }}">Domain Setting</a></li>
                             {% endif %}#}
                        </ul>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">KPI
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if (is_granted("ROLE_DOMAIN") or is_granted("ROLE_USER"))  %}
                            <li><a class="dropdown-item" href="{{ path('kpi_mark_location') }}">Location Mark</a></li>
                            <li><a class="dropdown-item" href="{{ path('kpi_employee_board') }}">KPI Board</a></li>
                            <li><a class="dropdown-item" href="{{ path('kpi_setup') }}">KPI Setup</a></li>
                            <li><a class="dropdown-item" href="{{ path('kpi_markchart') }}">Mark Chart</a></li>
                            {#              <li><a class="dropdown-item" href="{{ path('kpi_setting') }}">Setting</a></li>
                                          <li><a class="dropdown-item" href="{{ path('kpi_setting_new') }}">New Setting</a></li>
                          #}            {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="javascript:" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">CRM
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        {% if (is_granted("ROLE_DOMAIN") or is_granted("ROLE_USER"))  %}

                            <li><a class="dropdown-item" href="{{ path('crm_visit') }}">CRM Visit</a></li>
                            <li><a class="dropdown-item" href="{{ path('crm_customer') }}">Customer</a></li>
                            <li><a class="dropdown-item" href="{{ path('crm_chick') }}">Chick</a></li>
                            <li><a class="dropdown-item" href="{{ path('broiler_standard') }}">Broiler Standard </a></li>
                            <li><a class="dropdown-item" href="{{ path('sonali_standard') }}">Sonali Standard </a></li>
                            <li><a class="dropdown-item" href="{{ path('fcr') }}">FCR</a></li>
                            <li><a class="dropdown-item" href="{{ path('layer_performance_new') }}">Layer Performance</a></li>
                            <li><a class="dropdown-item" href="{{ path('layer_life_cycle') }}">Layer Life Cycle</a></li>
                            <li><a class="dropdown-item" href="{{ path('crm_expense') }}">Expense</a></li>
                            <li><a class="dropdown-item" href="{{ path('crm_setting') }}">Setting</a></li>

                        {% endif %}
                    </ul>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if app.user is  empty %}
                    <li class="search"><a href="#"><i class="fa fa-lock"></i></a></li>
                {% else %}
                    <li>
                        <div class="dropdown drp-user">
                            <a href="javascript:" style="color: #ffffff!important;" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="icon feather icon-user"></i> {{  app.user.username|capitalize }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right">
                                {% if app.user.name %}
                                    <div class="dropdown-header" >{{  app.user.name|capitalize }}</div>
                                    <div class="dropdown-divider"></div>
                                {% endif %}
                                <a class="dropdown-item" href="javascript:"><i class="feather icon-edit"></i> My account</a>
                                <a class="dropdown-item" href="javascript:"><i class="feather icon-file"></i> Documentation</a>
                                <a class="dropdown-item" href="javascript:"><i class="feather icon-help-circle"></i> Support</a>
                                <a class="dropdown-item" href="javascript:"><i class="feather icon-settings"></i> Shortcuts</a><div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ path('security_logout') }}"  title="Logout"><i class="feather icon-log-out"></i> Logout</a>
                            </div>
                        </div>
                    </li>
                {% endif %}
                {#  <li>
                      {% for locale in locales() %}
                      <a style="color: #ffffff!important;" {% if app.request.locale == locale.code %} class="lang_hide"{% else %} class="lang_show" {% endif %} href="{{ path(app.request.get('_route', 'blog_index'), app.request.get('_route_params', [])|merge({_locale: locale.code})) }}">{{ locale.name|capitalize|trans }}</a>
                      {% endfor %}
                  </li>#}
            </ul>
        </div>
    </nav>
</header>

templates/base.dist/sidebar.html.twig
<style>
    .dropdown-menu-right.show{
        top: 15px!important;
    }
    .dropdown-header {
        height: 67px;
    }
    .dropdown-item {
        display: block;
        width: 100%;
        padding: .25rem 1.5rem;
        clear: both;
        font-weight: 400;
        color: #212529;
        text-align: inherit;
        white-space: nowrap;
        background-color: transparent;
        border: 0;
        height: 70px;
    }
</style>
<nav class="pcoded-navbar">
    <div class="navbar-wrapper">
        <div class="navbar-brand header-logo">
            <a href="{{ path('app_dashboard') }}" class="b-brand">
                {% if app.user.terminal.coreDomain is not empty and  app.user.terminal.coreDomain.webPath is not empty %}
                    <img width="220" height="60" src="/{{ app.user.terminal.coreDomain.webPath }}">
                {% else %}
                    <img width="220" height="60" src="{{ asset('assets/images/default/logo-placeholder.png') }}">
                {% endif %}
            </a>
            {# <a class="mobile-menu" id="mobile-collapse" href="javascript:"><span></span></a>#}
        </div>
        <div class="navbar-content scroll-div">
            <ul class="nav pcoded-inner-navbar">
                <li  class="nav-item active">
                    <a href="{{ path('app_dashboard') }}" class="nav-link "><span class="pcoded-micon"><i class="feather icon-home"></i></span><span class="pcoded-mtext">Dashboard</span></a>
                </li>
                {% if app.user.hasRoles(['ROLE_PROCUREMENT','ROLE_DOMAIN']) and app.user.checkBundle(['procurement']) %}
                        {{ render(controller(
                            "App\\Controller\\ApplicationController::procurementMenu"
                        )) }}
                {% endif %}
                {% if app.user.hasRoles(['ROLE_INVENTORY','ROLE_DOMAIN']) and app.user.checkBundle(['inventory']) %}
                    <li class="nav-item pcoded-hasmenu">
                        <a class="" href="javascript:"><span class="pcoded-micon"><i class="feather icon-disc"></i></span><span class="pcoded-mtext">{{ "Inventory"|trans }}</span></a>
                        {{ render(controller(
                            "App\\Controller\\ApplicationController::inventoryMenu"
                        )) }}
                    </li>
                {% endif %}
                {% if app.user.hasRoles(['ROLE_PROCUREMENT_ADMIN','ROLE_DOMAIN']) and app.user.checkBundle(['procurement']) and app.user.terminal.businessGroup.slug == "bank" %}
                    <li class="nav-item pcoded-hasmenu">
                            {{ render(controller(
                                "App\\Controller\\ApplicationController::bankMenu"
                            )) }}
                    </li>
                {% endif %}
                {% if app.user.hasRoles(['ROLE_BUDGET','ROLE_DOMAIN']) and app.user.checkBundle(['budget']) %}
                    <li class="nav-item pcoded-hasmenu">
                        <a class="" href="javascript:"><span class="pcoded-micon"><i class="feather icon-at-sign"></i></span><span class="pcoded-mtext">{{ "Budget & Cost"|trans }}</span></a>
                        {{ render(controller(
                            "App\\Controller\\ApplicationController::budgetMenu"
                        )) }}

                    </li>
                {% endif %}
                {% if app.user.terminal.businessGroup.slug == "garment" %}
                    {% if app.user.hasRoles(['ROLE_DOMAIN','ROLE_DOMAIN_ADMIN']) and app.user.checkBundle(['garments']) %}
                        {{ render(controller(
                            "App\\Controller\\ApplicationController::garmentsMenu"
                        )) }}
                    {% endif %}
                {% endif %}
                {% if app.user.terminal.businessGroup.slug == "bank" %}
                    {{ render(controller(
                        "App\\Controller\\ApplicationController::bankMenu"
                    )) }}
                {% endif %}
                {% if app.user.terminal.businessGroup.slug == "poultry" %}
                    {% if app.user.hasRoles(['ROLE_DOMAIN','ROLE_DOMAIN_ADMIN']) and app.user.checkBundle(['poultry']) %}
                        {{ render(controller(
                            "App\\Controller\\ApplicationController::poultryMenu"
                        )) }}
                    {% endif %}
                {% endif %}
                {% if app.user.hasRoles(['ROLE_SBS','ROLE_DOMAIN']) and app.user.checkBundle(['security-billing']) %}
                    <li class="nav-item pcoded-hasmenu">
                        <a class="" href="javascript:"><span class="pcoded-micon"><i class="feather icon-at-sign"></i></span><span class="pcoded-mtext">{{ "Security Service"|trans }}</span></a>
                        {{ render(controller(
                            "App\\Controller\\ApplicationController::securityBillingMenu"
                        )) }}
                    </li>
                {% endif %}
                {% if app.user.hasRoles(['ROLE_DOMAIN','ROLE_DOMAIN_ADMIN','ROLE_PROCUREMENT_REPORT','ROLE_SBS_REPORT','ROLE_BUDGET_REPORT','ROLE_INVENTORY_REPORT']) %}
                    <li class="nav-item pcoded-hasmenu">
                        <a class="" href="javascript:"><span class="pcoded-micon"><i class="feather icon-bar-chart-2"></i></span><span class="pcoded-mtext">{{ "Reports"|trans }}</span></a>
                        {% if app.user.hasRoles(['ROLE_DOMAIN','ROLE_DOMAIN_ADMIN','ROLE_PROCUREMENT_REPORT']) and app.user.checkBundle(['procurement'])  %}
                            {{ render(controller(
                                "App\\Controller\\ApplicationController::procurementReportMenu"
                            )) }}
                        {% endif %}
                        {% if app.user.hasRoles(['ROLE_DOMAIN','ROLE_DOMAIN_ADMIN','ROLE_SBS_REPORT']) and app.user.checkBundle(['security-billing']) %}
                            {{ render(controller(
                                "App\\Controller\\ApplicationController::securityBillingReportMenu"
                            )) }}
                        {% endif %}
                    </li>
                {% endif %}
                {% if app.user.hasRoles(['ROLE_DOMAIN','ROLE_DOMAIN_ADMIN']) %}
                    <li class="nav-item pcoded-hasmenu">
                        <a class="" href="javascript:"><span class="pcoded-micon"><i class="feather icon-at-sign"></i></span><span class="pcoded-mtext">{{ "Administrator"|trans }}</span></a>
                        <ul class="sub-menu pcoded-submenu">
                            {% if app.user.terminal.businessGroup.slug == "security-billing" %}
                                <li><a href="{{ path('sbs_user') }}">{{ 'Employee'|trans }}</a></li>
                                <li><a href="{{ path('core_setting') }}">{{ 'Setting'|trans }}</a></li>
                            {% endif %}
                            {% if app.user.terminal.approveProcess == 1 %}
                                <li>
                                    <a href="javascript:">{{ 'Role & Permission'|trans }}</a>
                                    <ul class="sub-menu pcoded-submenu">
                                        <li><a href="{{ path('domain_moduleprocess') }}">{{ 'Module Process'|trans }}</a></li>
                                        <li><a href="{{ path('domain_bundlerole') }}">{{ 'Bundle Role'|trans }}</a></li>
                                    </ul>
                                </li>
                                <li><a href="{{ path('approval_user') }}">{{ 'Approval User'|trans }}</a></li>
                            {% endif %}
                            <li><a href="{{ path('domain_emailtemplate') }}">{{ 'Email Template'|trans }}</a></li>
                        </ul>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<header class="pcoded-header navbar-expand-lg navbar-light headerpos-fixed header-purple">
    <div class="m-header">
        <a class="mobile-menu" id="mobile-collapse1" href="javascript:"><span></span></a>
        <a href="/dashboard" class="b-brand">
            <div class="b-bg">
                <i class="feather icon-trending-up"></i>
            </div>
            <span class="b-title"></span>
        </a>
    </div>
    <a class="mobile-menu" id="mobile-header" href="javascript:">
        <i class="feather icon-more-horizontal"></i>
    </a>
    <div class="collapse navbar-collapse">
        <ul class="navbar-nav mr-auto">
            <li><a href="javascript:" class="full-screen" onclick="javascript:toggleFullScreen()"><i class="feather icon-maximize"></i></a></li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if app.user is  empty %}
                <li class="search"><a href="#"><i class="fa fa-lock"></i></a></li>
            {% else %}
                <li>
                    <div class="dropdown drp-user">
                        <a href="javascript:" style="color: #ffffff!important;" class="dropdown-toggle" data-toggle="dropdown">
                            <i class="icon feather icon-user"></i> {% if app.user.name %}{{  app.user.name|capitalize }}{% endif %}
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            {% if app.user.name %}
                                <div class="dropdown-header" >{{  app.user.name|capitalize }}</div>
                                <div class="dropdown-divider"></div>
                            {% endif %}
                            <a href="{{ path('profile_update') }}"><i class="feather icon-edit"></i> My account</a>
                            <a href="{{ path('change_password') }}"><i class="feather icon-lock"></i> Reset Password</a>
                            <a href="{{ path('security_logout') }}"  title="Logout"><i class="feather icon-log-out"></i> Logout</a>
                        </div>
                    </div>
                </li>
            {% endif %}
        </ul>
    </div>
</header>